# Generated by Django 3.2.5 on 2022-02-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220207_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
    ]
