# Generated by Django 3.2.5 on 2022-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220215_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ph_no',
            field=models.CharField(max_length=15),
        ),
    ]
