# Generated by Django 3.2.5 on 2022-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='team_id',
            field=models.ManyToManyField(blank=True, to='api.Teams'),
        ),
    ]
